# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
yarn_mappings=1.21.11+build.6
minecraft_version=1.21.11
loader_version=0.19.1
kotlin_loader_version=1.13.10+kotlin.2.3.20
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=arch.zero
archives_base_name=MinecraftWallpaperCreater
# Dependencies
# check this on https://maven.fabricmc.net/
fabric_version=0.141.3+1.21.11
hmcl_instance_dir=/home/archzero/.config/hmcl/.minecraft/versions/1.21.11-Fabric
modmenu_jar_name=modmenu-17.0.0.jar
cloth_config_jar_name=cloth-config-21.11.153-fabric.jar
